### ISSUE TITLE
Prepare setting the repositories to open source

### ISSUE THREAD

**Issue by janniclas** [fraunhofer-iem/dodo-database-service#50]
We want to publish our current state of work.
Therefore, we need to

- [ ] Make sure no sensitive information are in the code
- [ ] Cleanup the repositories
  - [ ] remove unused files
  - [ ] cleanup code
  - [ ] add documentation (readmes / how tos)
- [ ] figure out which licence is appropiate and add it to the repositories

**Comment by DieserFelix** [comment]
Can this issue be closed since you've set the repositories to public under GPL?
